apiVersion: v1
kind: Service
metadata:
  name: kubernetes-configmap-reload
spec:
  type: LoadBalancer
  selector:
    app: kubernetes-configmap-reload
  ports:
    - name: http
      protocol: TCP
      port: 8081

---
apiVersion: v1
kind: Deployment
metadata:
  name: kubernetes-configmap-reload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-configmap-reload
  template:
    metadata:
      labels:
        app: kubernetes-configmap-reload
    spec:
      containers:
        - name: kubernetes-configmap-reload
          image: sandeepnainala9/kubernetes-configmap-reload:latest
